# Generated by Django 5.1.4 on 2025-01-03 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_uploadedfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfiles',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfiles',
            name='published_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='uploadedfiles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
